import json
import os

import requests
from bs4 import BeautifulSoup

from constants import userAgentHeaders

# Manually set prices for pets that are missing or incorrect on the wiki
# But you should update the wiki instead!
petPriceOverrides = {
}

petNameOverrides = {
    "WISP;1": "DROPLET_WISP;1",
    "WISP;2": "FROST_WISP;2",
    "WISP;3": "GLACIAL_WISP;3",
    "WISP;4": "SUBZERO_WISP;4",
    "T-REX;4": "TYRANNOSAURUS;4"
}


def fetchData():
    apiUrl = "https://hypixelskyblock.minecraft.wiki/api.php"
    params = {
        "format": "json",
        "action": "parse",
        "prop": "text",
        "page": "George/Prices"
    }

    try:
        response = requests.get(apiUrl, params=params, headers=userAgentHeaders)
        response.raise_for_status()
        return response.json()
    except requests.RequestException as e:
        raise requests.RequestException(f"Error fetching data from {apiUrl}: {e}")
    except json.JSONDecodeError as e:
        raise ValueError(f"Error decoding JSON: {e}")


def processHtmlText(html):
    soup = BeautifulSoup(html, "html.parser")
    rows = soup.select("tr")
    del rows[0:2]  # remove headers

    result = {}
    for row in rows:
        columns = row.select("td")
        petName = columns[0].text.strip()
        del columns[0]
        sellPrices = []
        for column in columns:
            if (column.select_one("span.blankCell") or
                    "Not interested" in (price := column.text.strip())):
                sellPrices.append(None)
                continue

            price = price.replace(" Coins", "").replace(",", "")
            try:
                price = int(price)
            except ValueError:
                sellPrices.append(None)
                continue
            sellPrices.append(price)

        petId = petName.upper().replace(" ", "_")
        for i, price in enumerate(sellPrices):
            if price is None:
                continue
            indexedPetId = petId + ";" + str(i)
            indexedPetId = petNameOverrides.get(indexedPetId, indexedPetId)
            result[indexedPetId] = price
    return result


def addOverrides(result):
    for key, value in petPriceOverrides.items():
        result[key] = value


def Main():
    raw = fetchData()
    page = raw["parse"]["text"]["*"]
    petPrices = processHtmlText(page)
    addOverrides(petPrices)
    outputJson = {
        "license1": "Source: Hypixel SkyBlock Wiki (https://hypixelskyblock.minecraft.wiki/w/George/Prices)",
        "license2": "License: CC BY-NC-SA 3.0 (https://meta.weirdgloop.org/w/Licensing)",
        "notice": "This file is automatically generated and should not be modified manually. Please edit the `updateGeorgePrices.py` file instead.",
        "prices": petPrices
    }

    os.makedirs(os.path.dirname("constants/george.json"), exist_ok=True)
    with open("constants/george.json", "w") as json_file:
        json.dump(outputJson, json_file, indent=2, sort_keys=True)

    print(f"Saved {len(petPrices)} pet prices to george.json")


if __name__ == '__main__':
    Main()
