name: "Repo checks"

description: "Checks if all the files are fine."

inputs:
  repo-token:
    description: "Token with permissions to do repo things"

runs:
  using: "node12"
  main: "dist/index.js"