name: checks

# Controls when the action will run. 
on:
  pull_request:
    branches: [ master, alpha ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: run-checks
      uses: ./.github/actions/check-files
      with: 
        repo-token: ${{secrets.GITHUB_TOKEN}}

