name: checks

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, alpha ]
  pull_request:
    branches: [ master, alpha ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: DeDiamondPro/neu-repo-action
    - name: Run action
      run: #!/bin/bash
           npm i --only=prod
           node index.js
