name: checks

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, alpha ]
  pull_request:
    branches: [ master, alpha ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install dependencies
      run: npm i only=prod

    - name: run-checks
      uses: ./.github/actions/issue-maker
      with: 
        repo-token: ${{secrets.GITHUB_TOKEN}}

